weather.api.key=88f3be0477999ee465aef2d048785a23
weather.api.url=https://api.openweathermap.org/data/2.5/weather
supabase.url=https://dnbzlznhkedqzdpyrkui.supabase.co
supabase.key=sb_publishable_vXJxTLKKpelCZwu_JXUldA_09CDrlI5